### ISSUE TITLE
[BUG] USBIP功能不能使用

### ISSUE THREAD

**Issue by liuyu80** [kerms/wireless-esp32-tools#1]
**chip used**
esp32/esp32s3/esp32c3…

**To Reproduce**
1. `DAP_Thread()`任务里使用`ulTaskNotifyTake(pdFALSE, portMAX_DELAY)` 一直等待任务通知触发;
2. 在[commit](https://github.com/kerms/wireless-esp32-tools/commit/24aa3bed7f99bc7b081ed92cffebbd928b9ae1e9)中, 删除了`DAP_Thread()`任务的任务句柄和任务通知.

**Expected behavior**
恢复任务通知, usbip功能应该可以正常使用😀

**Comment by kerms** [comment]
感谢您的反馈，我当初查`kDAPTaskHandle`只有Give就误以为没有用，实际上它对应的是`DAP_handle.c::DAP_Thread::ulTaskNotifyTake(pdFALSE, portMAX_DELAY)`，我的锅。

commit: 3a5968f0fa54cf18b86bb1ebf667d2158ba3ba8c
